# Generated by Django 3.2.9 on 2022-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_branchgroupsummarymodel_bopeningbalace'),
    ]

    operations = [
        migrations.CreateModel(
            name='createcompanymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bopeningbalace', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Bledgersummarypagemodel',
        ),
        migrations.DeleteModel(
            name='BranchGroupSummaryModel',
        ),
    ]
