# Generated by Django 3.2.9 on 2022-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_bledgersummarypagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcompanymodel',
            name='bopeningbalace',
        ),
        migrations.AddField(
            model_name='branchgroupsummarymodel',
            name='bopeningbalace',
            field=models.IntegerField(default=0),
        ),
    ]
