# Generated by Django 3.2.9 on 2022-09-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20220902_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bledgersummarypagemodel',
            name='bclosingbalance',
        ),
        migrations.RemoveField(
            model_name='bledgersummarypagemodel',
            name='bcredit',
        ),
        migrations.RemoveField(
            model_name='bledgersummarypagemodel',
            name='bdebit',
        ),
        migrations.CreateModel(
            name='Bledgersummarypagevaluesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdebit', models.IntegerField()),
                ('bcredit', models.IntegerField()),
                ('bclosingbalance', models.IntegerField()),
                ('Branchsummary_frg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bledgersummarypagemodel')),
            ],
        ),
    ]
