# Generated by Django 3.2.9 on 2022-09-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220903_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bledgersummarypagevaluesmodel',
            name='Branchsummary_frg',
        ),
        migrations.DeleteModel(
            name='Bledgersummarypagemodel',
        ),
        migrations.DeleteModel(
            name='Bledgersummarypagevaluesmodel',
        ),
    ]
