# Generated by Django 3.2.9 on 2022-09-03 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_bledgersummarypagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='bledgervouchermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField(auto_now_add=True)),
                ('bperticular', models.CharField(max_length=250)),
                ('bvchtype', models.CharField(max_length=250)),
                ('bvchno', models.IntegerField()),
                ('bdebit', models.IntegerField()),
                ('bcredit', models.IntegerField()),
                ('bledgersummary_frgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bledgersummarypagemodel')),
            ],
        ),
    ]
