# Generated by Django 3.2.9 on 2022-09-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_bledgervouchermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesGroupSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sopeningbalace', models.IntegerField(default=0)),
                ('sperticulars', models.CharField(max_length=250)),
                ('sdebit', models.IntegerField()),
                ('scredit', models.IntegerField()),
                ('scompanyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.createcompanymodel')),
            ],
        ),
    ]
