# Generated by Django 3.2.9 on 2022-09-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_salesledgervouchermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseGroupSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popeningbalace', models.IntegerField(default=0)),
                ('pperticulars', models.CharField(max_length=250)),
                ('pdebit', models.IntegerField()),
                ('pcredit', models.IntegerField()),
                ('pcompanyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.createcompanymodel')),
            ],
        ),
    ]
