# Generated by Django 3.2.9 on 2022-09-06 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_delete_purchase_ledger_m_summarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_ledger_m_summarymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pperticulars', models.CharField(max_length=250)),
                ('pdebit', models.IntegerField()),
                ('pcredit', models.IntegerField()),
                ('pclosingbalance', models.IntegerField()),
                ('pBranchsummary_frgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.salesgroupsummarymodel')),
            ],
        ),
    ]
