# Generated by Django 3.2.9 on 2022-09-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_purchase_ledger_m_summarymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase_ledger_m_summarymodel',
        ),
    ]
