# Generated by Django 3.2.9 on 2022-09-06 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_purchase_ledger_m_summarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_ledgervouchermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.DateField(auto_now_add=True)),
                ('pperticular', models.CharField(max_length=250)),
                ('pvchtype', models.CharField(max_length=250)),
                ('pvchno', models.IntegerField()),
                ('pdebit', models.IntegerField()),
                ('pcredit', models.IntegerField()),
                ('pledgersummary_frgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_ledger_m_summarymodel')),
            ],
        ),
    ]
