# Generated by Django 3.2.9 on 2022-09-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_direct_groupsummarymodel_direct_ledger_m_summarymodel_direct_ledgervouchermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='createMonthmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=250)),
            ],
        ),
    ]
