# Generated by Django 3.2.9 on 2022-09-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20220907_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bledgersummarypagemodel',
            name='bperticulars',
        ),
    ]
